services:
  backend:
    build: ./backend
    container_name: freelas-backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: file:./dev.db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: freelas-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    stdin_open: true
    tty: true
